version: '3'
services:
  db:
    container_name: scanandgo_psql_db
    image: 'postgres' # use latest official postgres version
    environment:
      - POSTGRES_USER=dev-user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev-db
    volumes:
      - scanandgo_db:/db/scanandgo_psql_db/data
    ports:
      - '5464:5432'
volumes:
  scanandgo_db: {}